# Generated by Django 6.0.4 on 2026-04-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup Owner'), ('investor', 'Investor'), ('mentor', 'Mentor'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('parameters', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.startup')),
            ],
        ),
    ]
