# Generated by Django 6.0.4 on 2026-04-27 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investor_focus_areas_mentor_expertise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='startup',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='website',
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='market_potential',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='startup',
            name='scalability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='traction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
