# Generated by Django 6.0.4 on 2026-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_message_options_remove_startup_business_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
